version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-11-lein-2.9.3-node-browsers
        auth:
          username: victorbjelkholm
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - node_modules/
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run: npm test
